---
- include: keystone_credentials_keys_create.yml
  when: inventory_hostname == groups[openio_keystone_inventory_group][0]

- name: Fetch credentials tokens locally
  synchronize:
    mode: pull
    src: "{{ openio_keystone_credentials_tokens_key_repository }}"
    dest: "{{ openio_keystone_tmp_keys_dir }}/credential-keys"
    archive: yes
    delete: yes
  when: inventory_hostname == groups[openio_keystone_inventory_group][0]

- name: Copying credentials keys to all keystone hosts
  synchronize:
    mode: push
    src: "{{ openio_keystone_tmp_keys_dir }}/credential-keys"
    dest: "{{ openio_keystone_config_dir }}"
    archive: yes
    delete: yes
  when: inventory_hostname != groups[openio_keystone_inventory_group][0]

- name: Reset credentials keys ownership
  file:
    path: "{{ openio_keystone_credentials_tokens_key_repository }}"
    owner: root
    group: root
    state: directory
    recurse: yes
...
